# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://whw-baird.github.io/'
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Will Baird
  url:               https://twitter.com/whwbaird
  email:             wbaird@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
