# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://appdev-projects.github.io/'
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Raghu Betina
  url:               https://twitter.com/raghubetina
  email:             raghu@firstdraft.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
